// <auto-generated />
using System;
using CarlosCustodio_Ap1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarlosCustodio_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241011052827_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Cobros", b =>
                {
                    b.Property<int>("cobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("deudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("monto")
                        .HasColumnType("TEXT");

                    b.HasKey("cobroId");

                    b.HasIndex("deudorId");

                    b.ToTable("Cobros");

                    b.HasData(
                        new
                        {
                            cobroId = 1,
                            deudorId = 1,
                            fecha = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 2000m
                        });
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.CobrosDetalles", b =>
                {
                    b.Property<int>("detalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("prestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valorCobrado")
                        .HasColumnType("TEXT");

                    b.HasKey("detalleId");

                    b.HasIndex("cobroId");

                    b.HasIndex("prestamoId");

                    b.ToTable("CobrosDetalles");

                    b.HasData(
                        new
                        {
                            detalleId = 1,
                            cobroId = 1,
                            prestamoId = 1,
                            valorCobrado = 1000m
                        });
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Deudores", b =>
                {
                    b.Property<int>("deudorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("deudorId");

                    b.ToTable("Deudores");

                    b.HasData(
                        new
                        {
                            deudorId = 1,
                            Nombres = "Carlos"
                        });
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("prestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("deudorId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("monto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("prestamoId");

                    b.HasIndex("deudorId");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            prestamoId = 1,
                            balance = 3000m,
                            concepto = "Casa",
                            deudorId = 1,
                            monto = 5000m
                        });
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Cobros", b =>
                {
                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Deudores", "deudores")
                        .WithMany()
                        .HasForeignKey("deudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deudores");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.CobrosDetalles", b =>
                {
                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Cobros", "cobro")
                        .WithMany("cobroDetalles")
                        .HasForeignKey("cobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Prestamos", "prestamos")
                        .WithMany()
                        .HasForeignKey("prestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cobro");

                    b.Navigation("prestamos");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Prestamos", b =>
                {
                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Deudores", "deudores")
                        .WithMany()
                        .HasForeignKey("deudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deudores");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Cobros", b =>
                {
                    b.Navigation("cobroDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
