// <auto-generated />
using CarlosCustodio_Ap1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarlosCustodio_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240923235117_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Registro", b =>
                {
                    b.Property<int>("registroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("registroId");

                    b.ToTable("Registro");
                });
#pragma warning restore 612, 618
        }
    }
}
