// <auto-generated />
using System;
using CarlosCustodio_Ap1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarlosCustodio_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240930235930_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("prestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("deudor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("monto")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("prestamoId");

                    b.ToTable("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
