// <auto-generated />
using System;
using CarlosCustodio_Ap1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarlosCustodio_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Cobros", b =>
                {
                    b.Property<int>("cobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("deudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("monto")
                        .HasColumnType("TEXT");

                    b.HasKey("cobroId");

                    b.HasIndex("deudorId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.CobrosDetalles", b =>
                {
                    b.Property<int>("detalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("prestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valorCobrado")
                        .HasColumnType("TEXT");

                    b.HasKey("detalleId");

                    b.HasIndex("cobroId");

                    b.HasIndex("prestamoId");

                    b.ToTable("CobrosDetalles");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Deudores", b =>
                {
                    b.Property<int>("deudorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("deudorId");

                    b.ToTable("Deudores");

                    b.HasData(
                        new
                        {
                            deudorId = 1,
                            Nombres = "Carlos"
                        },
                        new
                        {
                            deudorId = 2,
                            Nombres = "Maria"
                        },
                        new
                        {
                            deudorId = 3,
                            Nombres = "Juancito"
                        });
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("prestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("deudorId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("monto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("prestamoId");

                    b.HasIndex("deudorId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Cobros", b =>
                {
                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Deudores", "deudores")
                        .WithMany()
                        .HasForeignKey("deudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deudores");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.CobrosDetalles", b =>
                {
                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Cobros", "cobro")
                        .WithMany("cobroDetalles")
                        .HasForeignKey("cobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Prestamos", "prestamos")
                        .WithMany()
                        .HasForeignKey("prestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cobro");

                    b.Navigation("prestamos");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Prestamos", b =>
                {
                    b.HasOne("CarlosCustodio_Ap1_P1.Models.Deudores", "deudores")
                        .WithMany()
                        .HasForeignKey("deudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("deudores");
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P1.Models.Cobros", b =>
                {
                    b.Navigation("cobroDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
